version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: ./docker
    container_name: my-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "4000:4000"

volumes:
  postgres-data:
